import { test, describe, before, after } from 'node:test';
import assert from 'node:assert';
import pg from 'pg';
import { pool } from '../src/database.js';
import { LABELS_TABLE } from '../src/labeler.js';
import { fetchLabelActivity, fetchRecentPostLabels } from '../src/label-activity.js';

const originalQuery = pool.query;

describe('Label activity (mocked database)', () => {
  after(() => {
    pool.query = originalQuery;
  });

  test('reports the total, last-hour count and latest label time from the label table', async () => {
    const calls: { sql: string; params: any[] }[] = [];
    pool.query = (async (sql: string, params: any[]) => {
      calls.push({ sql, params });
      return { rows: [{ total: 528909, last_cts: '2026-09-24T01:14:21.000Z', last_hour: 214 }] };
    }) as any;

    const activity = await fetchLabelActivity(new Date('2026-09-24T02:00:00.000Z'));
    assert.deepStrictEqual(activity, { total: 528909, lastHour: 214, lastLabelAt: '2026-09-24T01:14:21.000Z' });
    assert.ok(calls[0].sql.includes(LABELS_TABLE));
    assert.deepStrictEqual(calls[0].params, ['2026-09-24T01:00:00.000Z']);
  });

  test('handles an empty label table', async () => {
    pool.query = (async () => ({ rows: [{ total: 0, last_cts: null, last_hour: 0 }] })) as any;
    assert.deepStrictEqual(await fetchLabelActivity(), { total: 0, lastHour: 0, lastLabelAt: null });
  });

  test('groups recent labels by post, newest post first, labels in issue order', async () => {
    // The query returns labels newest first
    pool.query = (async () => ({
      rows: [
        { uri: 'at://b', val: 'world', cts: '2026-09-24T01:00:03.000Z' },
        { uri: 'at://a', val: 'politics', cts: '2026-09-24T01:00:02.000Z' },
        { uri: 'at://a', val: 'us', cts: '2026-09-24T01:00:01.000Z' },
      ],
    })) as any;

    assert.deepStrictEqual(await fetchRecentPostLabels(), [
      { uri: 'at://b', labels: ['world'], timestamp: '2026-09-24T01:00:03.000Z' },
      { uri: 'at://a', labels: ['us', 'politics'], timestamp: '2026-09-24T01:00:02.000Z' },
    ]);
  });
});

// Runs only against a disposable database. Never point this at the shared nytdata database.
const testDatabaseUrl = process.env.TEST_DATABASE_URL;

describe('Label activity (Postgres)', { skip: !testDatabaseUrl && 'TEST_DATABASE_URL is not set' }, () => {
  let testPool: pg.Pool;
  const schema = `nyt_activity_test_${Date.now()}_${Math.floor(Math.random() * 1e6)}`;
  const table = `"${schema}".labels`;

  before(async () => {
    testPool = new pg.Pool({ connectionString: testDatabaseUrl });
    await testPool.query(`CREATE SCHEMA "${schema}"`);
    // Same shape as the labeler library's table
    await testPool.query(`CREATE TABLE ${table} (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      src TEXT NOT NULL, uri TEXT NOT NULL, cid TEXT, val TEXT NOT NULL,
      neg BOOLEAN NOT NULL DEFAULT FALSE, cts TEXT NOT NULL, exp TEXT, sig BYTEA)`);
    const rows = [
      ['at://old', 'us', '2026-09-24T00:30:00.000Z'],
      ['at://a', 'us', '2026-09-24T01:10:00.000Z'],
      ['at://a', 'politics', '2026-09-24T01:10:00.010Z'],
      ['at://b', 'world', '2026-09-24T01:50:00.000Z'],
    ];
    for (const [uri, val, cts] of rows) {
      await testPool.query(`INSERT INTO ${table} (src, uri, val, cts) VALUES ('did:plc:x', $1, $2, $3)`, [uri, val, cts]);
    }
    // Run the real SQL against the test table instead of the app's
    pool.query = ((sql: string, params: any[]) => testPool.query(sql.replaceAll(LABELS_TABLE, table), params)) as any;
  });

  after(async () => {
    pool.query = originalQuery;
    await testPool.query(`DROP SCHEMA "${schema}" CASCADE`);
    await testPool.end();
  });

  test('counts all labels and those from the last hour', async () => {
    const activity = await fetchLabelActivity(new Date('2026-09-24T02:00:00.000Z'));
    assert.deepStrictEqual(activity, { total: 4, lastHour: 3, lastLabelAt: '2026-09-24T01:50:00.000Z' });
  });

  test('returns recent labels grouped by post', async () => {
    const posts = await fetchRecentPostLabels(3);
    assert.deepStrictEqual(posts, [
      { uri: 'at://b', labels: ['world'], timestamp: '2026-09-24T01:50:00.000Z' },
      { uri: 'at://a', labels: ['us', 'politics'], timestamp: '2026-09-24T01:10:00.010Z' },
    ]);
  });
});
