import { test, describe, before, after, beforeEach } from 'node:test';
import assert from 'node:assert';
import pg from 'pg';
import { pool, getActiveAuthors } from '../src/database.js';
import { metricsPool, POST_ARTICLES_TABLE } from '../src/post-articles.js';
import {
  fetchPopularArticlesReport, fetchAuthorsReport, fetchAuthorReport, resetReportCache, REPORT_WINDOWS, REPORT_LIMIT, REPORT_CACHE_MS,
} from '../src/reports.js';

const originalMetricsQuery = metricsPool.query;

describe('Popular articles report (mocked database)', () => {
  beforeEach(() => resetReportCache());
  after(() => {
    metricsPool.query = originalMetricsQuery;
    resetReportCache();
  });

  test('queries each period in order, newest first, on the metrics pool', async () => {
    const calls: any[][] = [];
    metricsPool.query = (async (_sql: string, params: any[]) => {
      calls.push(params);
      return { rows: [{ id: 1, title: `Top in ${params[0]}`, url: 'https://www.nytimes.com/a', authors: ['A'], shares: 2 }] };
    }) as any;

    const report = await fetchPopularArticlesReport();
    assert.deepStrictEqual(calls, [['1 hour', REPORT_LIMIT], ['8 hours', REPORT_LIMIT], ['24 hours', REPORT_LIMIT], ['7 days', REPORT_LIMIT]]);
    assert.deepStrictEqual(report.windows.map((w) => [w.key, w.label]), REPORT_WINDOWS.map((w) => [w.key, w.label]));
    assert.deepStrictEqual(report.windows[1].articles, [
      { id: 1, title: 'Top in 8 hours', url: 'https://www.nytimes.com/a', authors: ['A'], shares: 2 },
    ]);
  });

  test('reuses a report briefly and shares one set of queries between concurrent requests', async () => {
    let queries = 0;
    metricsPool.query = (async () => {
      queries++;
      await new Promise((resolve) => setTimeout(resolve, 5));
      return { rows: [] };
    }) as any;

    const now = Date.now();
    await Promise.all([fetchPopularArticlesReport(now), fetchPopularArticlesReport(now)]);
    assert.strictEqual(queries, REPORT_WINDOWS.length, 'Concurrent requests share one set of queries');

    await fetchPopularArticlesReport(now + REPORT_CACHE_MS - 1);
    assert.strictEqual(queries, REPORT_WINDOWS.length, 'A recent report is reused');

    await fetchPopularArticlesReport(now + REPORT_CACHE_MS);
    assert.strictEqual(queries, REPORT_WINDOWS.length * 2, 'An expired report is rebuilt');
  });

  test('does not cache a failed report', async () => {
    metricsPool.query = (async () => { throw new Error('statement timeout'); }) as any;
    await assert.rejects(fetchPopularArticlesReport(), /statement timeout/);
    metricsPool.query = (async () => ({ rows: [] })) as any;
    const report = await fetchPopularArticlesReport();
    assert.strictEqual(report.windows.length, REPORT_WINDOWS.length);
  });
});

// Runs only against a disposable database. Never point this at the shared nytdata database.
const testDatabaseUrl = process.env.TEST_DATABASE_URL;

describe('Popular articles report (Postgres)', { skip: !testDatabaseUrl && 'TEST_DATABASE_URL is not set' }, () => {
  // A schema of its own, so the nytdata tables and share table don't collide with other test files
  const schema = `nyt_reports_test_${Date.now()}_${Math.floor(Math.random() * 1e6)}`;
  let testPool: pg.Pool;

  before(async () => {
    testPool = new pg.Pool({ connectionString: testDatabaseUrl, options: `-c search_path=${schema}` });
    await testPool.query(`CREATE SCHEMA ${schema}`);
    // The nytdata tables the report reads, as the README describes them
    await testPool.query(`
      CREATE TABLE "Article" (id SERIAL PRIMARY KEY, url TEXT NOT NULL UNIQUE, section TEXT, subsection TEXT, title TEXT,
        date_created TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP); -- Prisma's type: no time zone, holds UTC
      CREATE TABLE "Author" (id SERIAL PRIMARY KEY, name TEXT NOT NULL);
      CREATE TABLE "_ArticleToAuthor" ("A" INTEGER NOT NULL REFERENCES "Article"(id), "B" INTEGER NOT NULL REFERENCES "Author"(id));
      CREATE TABLE post_articles (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, uri TEXT NOT NULL, author_did TEXT NOT NULL,
        article_id INTEGER NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE (uri, article_id));
      INSERT INTO "Article" (id, url, section, title, date_created) VALUES
        (1, 'https://www.nytimes.com/one.html', 'us', 'One', '2026-09-26 03:30:00'),
        (2, 'https://www.nytimes.com/two.html', 'opinion', 'Two', '2026-09-27 14:05:00'),
        (3, 'https://www.nytimes.com/three.html', 'world', 'Three', '2026-09-25 12:00:00'),
        (4, 'https://www.nytimes.com/four.html', 'arts', NULL, '2026-09-24 12:00:00'),
        -- Never shared (e.g. from before recording began)
        (5, 'https://www.nytimes.com/five.html', 'us', 'Five', '2026-09-20 12:00:00'),
        (6, 'https://www.nytimes.com/six.html', 'arts', 'Six', '2026-09-10 12:00:00');

      INSERT INTO "Author" (id, name) VALUES (1, 'Zoe Writer'), (2, 'Adam Author');
      INSERT INTO "_ArticleToAuthor" ("A", "B") VALUES (1, 1), (1, 2), (2, 1);
      INSERT INTO "Author" (id, name) VALUES (3, 'Nobody Shared');
      INSERT INTO "_ArticleToAuthor" ("A", "B") VALUES (5, 1), (6, 3);
      -- Who gets a label: 2+ opinion articles (Zoe: 2 and 5; Unshared Columnist: 7 and 8), or
      -- 2+ US politics articles (Adam: 1 and 9, in mixed case). Staff Reporter has shares
      -- (article 3) but no label; Nobody Shared has neither.
      UPDATE "Article" SET subsection = 'politics' WHERE id = 1;
      UPDATE "Article" SET section = 'opinion' WHERE id = 5;
      INSERT INTO "Article" (id, url, section, subsection, title, date_created) VALUES
        (7, 'https://www.nytimes.com/seven.html', 'opinion', NULL, 'Seven', '2026-09-15 12:00:00'),
        (8, 'https://www.nytimes.com/eight.html', 'opinion', NULL, 'Eight', '2026-09-16 12:00:00'),
        (9, 'https://www.nytimes.com/nine.html', 'US', 'Politics', 'Nine', '2026-09-17 12:00:00');
      INSERT INTO "Author" (id, name) VALUES (4, 'Unshared Columnist'), (5, 'Staff Reporter');
      INSERT INTO "_ArticleToAuthor" ("A", "B") VALUES (7, 4), (8, 4), (9, 2), (3, 5);
    `);
    // Shares at different ages: article 1 is recent, article 2 older, article 3 only last week
    const shares: [number, string][] = [
      [1, '10 minutes'], [1, '20 minutes'], [2, '30 minutes'],
      [2, '2 hours'], [2, '3 hours'], [1, '5 hours'],
      [3, '12 hours'], [3, '13 hours'], [3, '14 hours'], [3, '15 hours'],
      [3, '3 days'], [4, '4 days'],
      [1, '8 days'], // Too old for every period
    ];
    let post = 0;
    for (const [articleId, age] of shares) {
      await testPool.query(
        `INSERT INTO post_articles (uri, author_did, article_id, created_at) VALUES ($1, 'did:plc:x', $2, now() - $3::interval)`,
        [`at://did:plc:x/app.bsky.feed.post/${post++}`, articleId, age],
      );
    }
    // Run the real SQL against this schema
    metricsPool.query = ((sql: string, params: any[]) => testPool.query(sql.replaceAll(POST_ARTICLES_TABLE, 'post_articles'), params)) as any;
    resetReportCache();
  });

  after(async () => {
    metricsPool.query = originalMetricsQuery;
    resetReportCache();
    await testPool.query(`DROP SCHEMA ${schema} CASCADE`);
    await testPool.end();
    await metricsPool.end();
    await pool.end();
  });

  test('counts shares per period, most shared first, with authors', async () => {
    const report = await fetchPopularArticlesReport();
    const summary = Object.fromEntries(report.windows.map((w) => [w.key, w.articles.map((a) => [a.title, a.shares])]));
    assert.deepStrictEqual(summary, {
      '1h': [['One', 2], ['Two', 1]],
      '8h': [['One', 3], ['Two', 3]], // A tie goes to the most recently shared
      '24h': [['Three', 4], ['One', 3], ['Two', 3]],
      '7d': [['Three', 5], ['One', 3], ['Two', 3], [null, 1]],
    });

    const one = report.windows[0].articles[0];
    assert.deepStrictEqual(one, {
      id: 1, title: 'One', url: 'https://www.nytimes.com/one.html', authors: ['Adam Author', 'Zoe Writer'], shares: 2,
    });
    // An article without authors gets an empty list; one without a title keeps its URL
    const four = report.windows[3].articles[3];
    assert.deepStrictEqual([four.authors, four.url], [[], 'https://www.nytimes.com/four.html']);
  });

  test('lists the label authors with a shared article, most shared first', async () => {
    const report = await fetchAuthorsReport();
    // Article 1 (Adam and Zoe) was shared 4 times in all, article 2 (Zoe) 3 times. Staff
    // Reporter's article 3 was shared most, but they don't get a label
    assert.deepStrictEqual(report.authors, [
      { id: 1, name: 'Zoe Writer', articles: 2, shares: 7 },
      { id: 2, name: 'Adam Author', articles: 1, shares: 4 },
    ]);
  });

  test("returns an author's shared articles with their dates in UTC", async () => {
    const report = await fetchAuthorReport(1);
    assert.deepStrictEqual(report!.author, { id: 1, name: 'Zoe Writer' });
    assert.deepStrictEqual(report!.articles, [
      { id: 1, title: 'One', url: 'https://www.nytimes.com/one.html', dateAdded: '2026-09-26T03:30:00.000Z', shares: 4 },
      { id: 2, title: 'Two', url: 'https://www.nytimes.com/two.html', dateAdded: '2026-09-27T14:05:00.000Z', shares: 3 },
    ]);
  });

  test('returns null for an unknown author, and no articles for one never shared', async () => {
    assert.strictEqual(await fetchAuthorReport(999), null);
    const unshared = await fetchAuthorReport(3);
    assert.deepStrictEqual([unshared!.author.name, unshared!.articles], ['Nobody Shared', []]);
  });

  test('with every article, lists all label authors and counts all of their articles', async () => {
    const report = await fetchAuthorsReport('all');
    assert.strictEqual(report.scope, 'all');
    assert.deepStrictEqual(report.authors, [
      { id: 1, name: 'Zoe Writer', articles: 3, shares: 7 }, // Articles 1, 2 and the unshared 5
      { id: 2, name: 'Adam Author', articles: 2, shares: 4 }, // Articles 1 and the unshared 9
      { id: 4, name: 'Unshared Columnist', articles: 2, shares: 0 },
    ]);
    // Authors without a label are never listed, shared or not
    assert.ok(!report.authors.some((author) => ['Staff Reporter', 'Nobody Shared'].includes(author.name)));
    // The default is unchanged
    assert.deepStrictEqual((await fetchAuthorsReport()).authors.map((a) => a.name), ['Zoe Writer', 'Adam Author']);
  });

  test("with every article, includes an author's unshared articles with 0 shares", async () => {
    const zoe = await fetchAuthorReport(1, 'all');
    assert.deepStrictEqual(zoe!.articles.map((a) => [a.title, a.shares, a.dateAdded]), [
      ['One', 4, '2026-09-26T03:30:00.000Z'],
      ['Two', 3, '2026-09-27T14:05:00.000Z'],
      ['Five', 0, '2026-09-20T12:00:00.000Z'],
    ]);
    const nobody = await fetchAuthorReport(3, 'all');
    assert.deepStrictEqual(nobody!.articles.map((a) => [a.title, a.shares]), [['Six', 0]]);
  });

  test('lists exactly the authors the labeler issues author labels for', async () => {
    const originalPoolQuery = pool.query;
    pool.query = ((sql: string, params: any[]) => testPool.query(sql, params)) as any;
    try {
      const labeler = (await getActiveAuthors()).map((author) => author.name).sort();
      const report = (await fetchAuthorsReport('all')).authors.map((author) => author.name).sort();
      assert.deepStrictEqual(report, labeler);
    } finally {
      pool.query = originalPoolQuery;
    }
  });
});
